### ISSUE TITLE
Generated image size

### ISSUE THREAD

**Issue by zhangyupeng123** [limuloo/MIGC#10]
Is the image size generated by this method fixed?

**Comment by limuloo** [comment]
@zhangyupeng123 The inference code currently provided can generate images whose length and width are divisible by 8, such as 768 and 1024.

**Comment by zhangyupeng123** [comment]
@limuloo Could you please let us know where this parameter is set? We haven't been able to find its location yet.

**Comment by limuloo** [comment]
@zhangyupeng123 https://github.com/limuloo/MIGC/blob/68f4dcf15c105865df94384790bec0e1de99fb48/migc/migc_pipeline.py#L622
see 'height' and 'width' parameter.

**Comment by zhangyupeng123** [comment]
@limuloo Okay, thank you for your guidance.
